# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     5
paginate_path: "page:num"

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     redcarpet
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#站点基础配置
title: Chan's Blog
subTitle: Just a blog.
description: 这是 Chan 的博客，它是基于 Jekyll 搭建起来的。
url: http://007sair.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 标签
    url: /categories.html
    icon: icon-tags
    class: none
  - text: 归档
    url: /archives.html
    icon: icon-bookmark
    class: none
  - text: Link
    url: /links.html
    icon: icon-link
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-user
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: Chan

#多说评论
comments :
    provider : duoshuo
    duoshuo : 
      short_name : sair

